// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7dyrlP6IxbcN4fUK-uypfvhv7epXiShM',
    appId: '1:371137694883:web:0e50ec8562d10754884316',
    messagingSenderId: '371137694883',
    projectId: 'unihack-database-58df5',
    authDomain: 'unihack-database-58df5.firebaseapp.com',
    storageBucket: 'unihack-database-58df5.appspot.com',
    measurementId: 'G-Z364MRTV6G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2YZOnPj0t4SbPlCCkLJQ416m3Y2tXf4s',
    appId: '1:371137694883:android:d547535e065c612e884316',
    messagingSenderId: '371137694883',
    projectId: 'unihack-database-58df5',
    storageBucket: 'unihack-database-58df5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBv2oOQIktSjbl3F_JsBxfxv6XywHR0268',
    appId: '1:371137694883:ios:9688111d2a1eb3d0884316',
    messagingSenderId: '371137694883',
    projectId: 'unihack-database-58df5',
    storageBucket: 'unihack-database-58df5.appspot.com',
    iosBundleId: 'com.example.unihack2023',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBv2oOQIktSjbl3F_JsBxfxv6XywHR0268',
    appId: '1:371137694883:ios:e45790187b5824db884316',
    messagingSenderId: '371137694883',
    projectId: 'unihack-database-58df5',
    storageBucket: 'unihack-database-58df5.appspot.com',
    iosBundleId: 'com.example.unihack2023.RunnerTests',
  );
}
